### ISSUE TITLE
Whitespace in Lowfat

### ISSUE THREAD

**Issue by jonathanrobie** [Clear-Bible/macula-greek#22]
Whitespace in Lowfat has changed in ways that make it harder to read in some editors.

Could we please restore whitespace to the previous form?  This is probably as simple as running the transform originally used to create it, making sure we keep all the attributes.

**Comment by klosoter** [comment]
This probably happened because of me. The Python library I use (lxml) puts all attributes on the same line as the element. As far as I know, there are no easy ways (with Python) to change the formatting of a XML file. So, it will probably happen again when I make new commits. 

Any ideas on how to avoid this problem?

**Comment by ryderwishart** [comment]
I can regenerate the lowfat trees right now on your branch. However, did we resolve the nodes that were getting dropped?

**Comment by klosoter** [comment]
I did

**Comment by klosoter** [comment]
Also, I made some changes in lowfat (there were duplicate xml:id) and some Node/m that should have been wg/w.

**Comment by klosoter** [comment]
This is about macula-hebrew right? @ryderwishart

**Comment by ryderwishart** [comment]
Yes that's right @klosoter. Didn't notice it was the wrong repo. 🤦‍♂️
