### ISSUE TITLE
Mappings needed

### ISSUE THREAD

**Issue by themikejr** [Clear-Bible/macula-greek#40]
For lowfat greek trees, the Dashboard team will need a mapping file similar to [morpheme-mappings.xml](https://github.com/Clear-Bible/macula-hebrew/blob/main/mappings/morpheme-mappings.xml). in the hebrew repo. I do not currently see something analogous here in `macula-greek`.

**Comment by jonathanrobie** [comment]
Is this what you need?

https://github.com/Clear-Bible/macula-greek/tree/main/sources/Clear/mappings

**Comment by themikejr** [comment]
It would be good if we could use the same mapping format (xml, tsv, etc...) between the hebrew and greek repos, but this appears to be the data the dashboard team will need. I didn't see it because I expected it to be in the top level `mappings/` directory like it is in `macula-hebrew`.

Additionally, it looks like the IDs for Nestle1904 in the greek map need to be updated to reflect the new `n` prefixed format.

**Comment by jonathanrobie** [comment]
The `n` prefix is now there for IDs.

I agree that we should use the same conventions for `macula-greek` and `macula-hebrew`.  How about this:

- Use TSV for mappings in both repositories
- Put the TSV in a `$root/mappings` subdirectory

**Comment by RickBrannan** [comment]
Following up here because it seems appropriate. 

@jonathanrobie asked me to make an XML version of the Greek `$root/macula-greek/sources/Clear/mappings/mappings-GNT-stripped.tsv` file. I don't see an `n` prefix in the TSV. And I don't see the TSV in the `macula-greek/mappings` folder. (I thought I would after reading the above discussion).

I have an XML form of the TSV ready to commit. Do we need to put them in `$root/mappings` instead of/in addition to the `$root/sources/Clear/mappings` folder?

**Comment by jonathanrobie** [comment]
I believe these mappings are done, and are found here:

https://github.com/Clear-Bible/macula-greek/tree/main/sources/Clear/mappings
