### ISSUE TITLE
Presence of non-puncutation characters in TSV `after` column

### ISSUE THREAD

**Issue by themikejr** [Clear-Bible/macula-greek#88]
In the Macula Greek SBLTGNT TSV, I encountered an unexpected value in the `after` column. I understood the `after` to contain punctuation that can be joined to the value of the `text` column for a given token.

Row `1876` (id `n40005017011`) contains the value `κ` (Kappa) in the `after` column. When appended to the value of the text, you get `οὐκ`, which could be a valid word. I'm not sure why the final character has been separated.

The presence of non-punctuation values in the `after` column impacts how the data is used. It would be good to identify this as intentional vs. oversight.

**Comment by jacobwegner** [comment]
We're taking a closer look at this.  The Nestle1904 nodes data differs from the SBLGNT nodes data in how the `NormalizedForm` value has been populated.

`NormalizedForm` is used to populate the `after` attribute in Lowfat and the TSV exports, so if we are able to make a change to the SBLGNT nodes, we should be able to propagate that change forward.

**Comment by jonathanrobie** [comment]
Node:

<img width="1487" alt="image" src="https://github.com/Clear-Bible/macula-greek/assets/1767869/49a726bf-c686-4102-a4f2-c0342cef1cf1">

Lowfat:
<img width="236" alt="image" src="https://github.com/Clear-Bible/macula-greek/assets/1767869/52bf89b9-0bfb-42ce-ac88-513c08ec5edd">

**Comment by jonathanrobie** [comment]
OK, I think I can diagnose the problem.   The code assumes that the `@NormalizedForm` attribute has the complete normalized word, minus punctuation.  If the `string-length()` of `@NormalizedForm` is `N` and the element text is, say, `N + 1`, then it assumes anything after the first `N` characters of the e "οὐκ",lement belongs in `@after`.

This works fine for Nestle1904 because the element text is "οὐκ" and the `@NormalizedForm` is also "οὐκ".

For SBLGNT, the element text is "οὐκ", the `@NormalizedForm` is (incorrectly) "οὐ", so it assumes the last character of the element text belongs in `@after`.  The solution is to correct `@NormalizedForm` to "οὐκ".

**Comment by jonathanrobie** [comment]
The only two clearly wrong `@after` values I can find are both instances of the same problem - `@NormalizedForm` is wrong, and has the wrong length, for either οὐχ or οὐκ.

I think the solution is to fix those values in Node.

**Comment by RickBrannan** [comment]
I believe this is addressed for SBLGNT with this PR: https://github.com/Clear-Bible/macula-greek/pull/89

**Comment by jacobwegner** [comment]
Fixed in the [24.03.15](https://github.com/Clear-Bible/macula-greek/releases/tag/24.03.15) release.
